Update run_tests.yml

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -37,10 +37,11 @@ jobs:
             -H "X-GitHub-Api-Version: 2022-11-28" \
             "https://api.github.com/repos/xJennyx/run-tests-demo/actions/artifacts")
 
-          ARTIFACT_ID=$(echo "$ARTIFACT_INFO" | python3 -c "import sys, json; artifacts=json.load(sys.stdin)['artifacts']; print(next((a['id'] for a in artifacts if a['name'] == 'allure-results'), ''))")
+          ARTIFACT_ID=$(echo "$ARTIFACT_INFO" | python3 -c "import sys, json; artifacts=json.load(sys.stdin).get('artifacts', []); print(next((a['id'] for a in artifacts if a['name'] == 'allure-results'), ''))")
 
           if [ -z "$ARTIFACT_ID" ]; then
             echo "❌ No previous 'allure-results' artifact found. Skipping download."
+            touch skip.txt  # просто чтобы был какой-то файл
             exit 0
           fi
 
@@ -53,10 +54,15 @@ jobs:
             -o artifacts.zip
 
       - name: Extract history
-        if: exists('artifacts.zip')
         run: |
-          mkdir -p allure-results
-          unzip -q artifacts.zip -d allure-results || echo "No files to unzip"
+          if [ -f artifacts.zip ]; then
+            echo "📂 Unzipping..."
+            mkdir -p allure-results
+            unzip -q artifacts.zip -d allure-results || echo "⚠️ Nothing to unzip"
+          else
+            echo "⚠️ artifacts.zip not found, skipping unzip"
+            mkdir -p allure-results
+          fi
 
       - name: Upload history for next job
         uses: actions/upload-artifact@v4
